# Generated by Django 2.1.1 on 2018-09-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, verbose_name='Name')),
                ('surname', models.CharField(max_length=22, verbose_name='Surname')),
                ('address', models.TextField(verbose_name='Address')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('tlf', models.CharField(max_length=22, null=True, verbose_name='Telephone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('monday', models.BooleanField(default=False, verbose_name='Monday')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Tuesday')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Wednesday')),
                ('thursday', models.BooleanField(default=False, verbose_name='Thursday')),
                ('friday', models.BooleanField(default=False, verbose_name='Friday')),
                ('saturday', models.BooleanField(default=False, verbose_name='Saturday')),
                ('sunday', models.BooleanField(default=False, verbose_name='Sunday')),
                ('fromto', models.CharField(default='07:00', max_length=8, verbose_name='From:')),
                ('to', models.CharField(default='14:00', max_length=8, verbose_name='To:')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Voluntary',
                'verbose_name_plural': 'Voluntaries',
                'ordering': ['name'],
            },
        ),
    ]
