# Generated by Django 2.1.1 on 2018-09-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False, verbose_name='Monday')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Tuesday')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Wednesday')),
                ('thursday', models.BooleanField(default=False, verbose_name='Thursday')),
                ('friday', models.BooleanField(default=False, verbose_name='Friday')),
                ('saturday', models.BooleanField(default=False, verbose_name='Saturday')),
                ('sunday', models.BooleanField(default=False, verbose_name='Sunday')),
                ('fromto', models.CharField(default='07:00', max_length=8, verbose_name='From:')),
                ('to', models.CharField(default='14:00', max_length=8, verbose_name='To:')),
            ],
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='fromto',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='to',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='horarios',
            name='voluntary',
            field=models.ManyToManyField(related_name='get_posts', to='voluntary.Voluntary', verbose_name='Categorías'),
        ),
    ]
